spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.115.159.245:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true
    username: pkpm1
    password: Pkpm=123
mybatis:
  mapper-locations: classpath:/mapper/*.xml